# Generated by Django 5.1.3 on 2024-11-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('validacion', models.BooleanField()),
                ('input_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('validacion', models.BooleanField()),
                ('input_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_url', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('validacion', models.BooleanField()),
                ('input_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
