# Generated by Django 5.1.3 on 2024-11-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='email',
            name='validacion',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='validacion',
        ),
        migrations.RemoveField(
            model_name='url',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='url',
            name='validacion',
        ),
    ]
