# Generated by Django 5.1.3 on 2024-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_remove_email_descripcion_remove_email_validacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
