# Generated by Django 5.1.3 on 2024-11-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_email_is_valid_phone_is_valid_url_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_valid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_valid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='url',
            name='is_valid',
            field=models.CharField(max_length=100),
        ),
    ]
