# Generated by Django 5.1.3 on 2024-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0004_alter_email_is_valid_alter_phone_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.CharField(default='No message', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='message',
            field=models.CharField(default='No message', max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='message',
            field=models.CharField(default='No message', max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
