# Generated by Django 5.1.3 on 2024-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0006_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='message_sms',
            field=models.CharField(max_length=300),
        ),
    ]
