# Generated by Django 5.1.3 on 2024-11-21 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0007_alter_sms_message_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='input_at_local',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phone',
            name='input_at_local',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sms',
            name='input_at_local',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='url',
            name='input_at_local',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
