# Generated by Django 5.1.3 on 2024-11-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0008_email_input_at_local_phone_input_at_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='input_at_local',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='input_at_local',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='input_at_local',
        ),
        migrations.RemoveField(
            model_name='url',
            name='input_at_local',
        ),
    ]
