# Generated by Django 5.1.3 on 2024-11-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
